# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.50/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  id: 9nr-IV4
  title: Default page
