# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.50/docs/schemas/v1/definitions.json#properties/Theme

apiVersion: v1
kind: theme
spec:
  options:
    palette:
      mode: light
      primary:
        main: "#f44336"
        contrastText: "#fff"
      secondary:
        main: "#3f51b5"
        contrastText: "#fff"
