# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.50/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: PETROL Test Page
  alias:
    - afzL2D9
  content:
    - component: Container
      name: header
      children:
        - component: PageRow
          name: pageRow1
          props:
            justifyContent: start
            gap:
              $$jsExpression: ""
          children:
            - component: Image
              name: image1
              props:
                src: https://www.petrol.eu/webfiles/1703675865451/common/images/brand/petrol.svg
                alt: PETROL
                fit: contain
                width: 158
                height: 48
                loading: false
              layout:
                columnSize: 1.6098880818099661
                verticalAlign: center
            - component: Text
              name: link1
              layout:
                columnSize: 0.39011191819003377
                verticalAlign: center
                horizontalAlign: end
              props:
                mode: link
                value: KONTAKTI
                openInNewTab: false
                href: ""
                sx:
                  margin-right: 20
      props:
        sx:
          border: 0px solid black
          borderRadius: 10
    - component: Text
      name: text
      props:
        value: Hello Petrol Dev Team!
        variant: h4
        sx:
          margin-top: 50
    - component: Text
      name: text1
      props:
        value: This are my dogs from the supabase
        variant: subtitle1
        sx:
          margin-bottom: 50
    - component: DataGrid
      name: dataGrid
      props:
        rows:
          $$jsExpression: dogQuery.data
        columns:
          - field: "0"
            type: string
          - field: "1"
            type: json
        loading: false
        height: 432
        hideToolbar: false
        density: compact
        rowsSource: prop
        dataProviderId: dogQuery.data;.ts:default
        rowIdField: null
    - component: Paper
      name: paper
      props:
        elevation: 10
      children:
        - component: PageRow
          name: pageRow
          props:
            justifyContent: start
          children:
            - component: Image
              name: image
              layout:
                horizontalAlign: start
                verticalAlign: start
              props:
                src:
                  $$jsExpression: imgQuery.data.message
                fit: contain
                sx:
                  border: 10px solid black
                  bgcolor: "#000000"
            - component: Text
              name: link
              layout:
                columnSize: 1
                horizontalAlign: end
                verticalAlign: end
              props:
                mode: link
                value: Link do slike
                href:
                  $$jsExpression: imgQuery.data.message
                openInNewTab: true
                loading: false
    - component: codeComponent.PetrolCard
      name: petrolCard
      layout:
        columnSize: 0.488557290601938
      props:
        msg:
          $$jsExpression: petrolCard.msg
  displayName: PETROL Test Page
  display: standalone
  queries:
    - name: dogQuery
      mode: query
      query:
        kind: rest
        url: https://dog.ceo/api/breeds/list/all
        headers: []
        method: GET
        transform: return Object.entries(data.message);
        transformEnabled: true
        searchParams: []
    - name: imgQuery
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression: "`https://dog.ceo/api/breed/${parameters.breed}/images/random`"
        headers: []
        method: GET
        searchParams: []
        transform: "`https://dog.ceo/api/breed/${parameters.breed}/images/random`"
        transformEnabled: false
      parameters:
        - name: breed
          value:
            $$jsExpression: dataGrid.selection?.[0] ?? 'akita'
